In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[84, 9851, 608, 1152],
 [84, 9851, 608, 8627],
 [84, 7156, 608, 1224],
 [9449, 7228, 2438, 2744, 53],
 [9449, 7228, 2438, 2744, 3359],
 [2287, 84, 3045, 608, 399],
 [9682, 9156, 230, 2744]]

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0   84 9851  608 1152]
 [   0    0    0    0   84 9851  608 8627]
 [   0    0    0    0   84 7156  608 1224]
 [   0    0    0 9449 7228 2438 2744   53]
 [   0    0    0 9449 7228 2438 2744 3359]
 [   0    0    0 2287   84 3045  608  399]
 [   0    0    0    0 9682 9156  230 2744]]


In [10]:
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 149ms/step


array([[[ 0.01393092,  0.01602132,  0.02326587, -0.00346471,
          0.01686013, -0.01429564,  0.01043053,  0.03962778,
         -0.04411152, -0.04411011],
        [ 0.01393092,  0.01602132,  0.02326587, -0.00346471,
          0.01686013, -0.01429564,  0.01043053,  0.03962778,
         -0.04411152, -0.04411011],
        [ 0.01393092,  0.01602132,  0.02326587, -0.00346471,
          0.01686013, -0.01429564,  0.01043053,  0.03962778,
         -0.04411152, -0.04411011],
        [ 0.01393092,  0.01602132,  0.02326587, -0.00346471,
          0.01686013, -0.01429564,  0.01043053,  0.03962778,
         -0.04411152, -0.04411011],
        [ 0.01038728, -0.03843895,  0.02582094, -0.01184576,
         -0.03273486,  0.04870221, -0.04384736,  0.04298903,
          0.03649363,  0.0438208 ],
        [ 0.00972707, -0.03637459, -0.04496793, -0.02066236,
          0.00807314,  0.00674139,  0.02500507, -0.00477431,
         -0.04223584,  0.0418952 ],
        [ 0.03075268,  0.0034161 ,  0.02347336, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0,   84, 9851,  608, 1152])