In [7]:
import nltk 
nltk.download('gutenberg')
from nltk.corpus import gutenberg
import pandas as pd


[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [8]:
data=gutenberg.raw('shakespeare-hamlet.txt')


In [9]:
with open('hamlet.txt','w') as file:
    file.write(data)

In [10]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

In [11]:
with open('hamlet.txt','r') as file:
    text=file.read().lower()

In [12]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts([text])
total_words=len(tokenizer.word_index)+1

In [13]:
total_words

4818

In [14]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'i': 5,
 'you': 6,
 'a': 7,
 'my': 8,
 'it': 9,
 'in': 10,
 'that': 11,
 'ham': 12,
 'is': 13,
 'not': 14,
 'his': 15,
 'this': 16,
 'with': 17,
 'your': 18,
 'but': 19,
 'for': 20,
 'me': 21,
 'lord': 22,
 'as': 23,
 'what': 24,
 'he': 25,
 'be': 26,
 'so': 27,
 'him': 28,
 'haue': 29,
 'king': 30,
 'will': 31,
 'no': 32,
 'our': 33,
 'we': 34,
 'on': 35,
 'are': 36,
 'if': 37,
 'all': 38,
 'then': 39,
 'shall': 40,
 'by': 41,
 'thou': 42,
 'come': 43,
 'or': 44,
 'hamlet': 45,
 'good': 46,
 'do': 47,
 'hor': 48,
 'her': 49,
 'let': 50,
 'now': 51,
 'thy': 52,
 'how': 53,
 'more': 54,
 'they': 55,
 'from': 56,
 'enter': 57,
 'at': 58,
 'was': 59,
 'oh': 60,
 'like': 61,
 'most': 62,
 'there': 63,
 'well': 64,
 'know': 65,
 'selfe': 66,
 'would': 67,
 'them': 68,
 'loue': 69,
 'may': 70,
 "'tis": 71,
 'vs': 72,
 'sir': 73,
 'qu': 74,
 'which': 75,
 'did': 76,
 'why': 77,
 'laer': 78,
 'giue': 79,
 'thee': 80,
 'ile': 81,
 'must': 82,
 'hath': 

In [15]:
input_sequences=[]
for line in text.split('\n'):
    token_list=tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram_sequence=token_list[:i+1]
        input_sequences.append(n_gram_sequence)
        input_sequences.append(n_gram_sequence)

In [16]:
input_sequences

[[1, 687],
 [1, 687],
 [1, 687, 4],
 [1, 687, 4],
 [1, 687, 4, 45],
 [1, 687, 4, 45],
 [1, 687, 4, 45, 41],
 [1, 687, 4, 45, 41],
 [1, 687, 4, 45, 41, 1886],
 [1, 687, 4, 45, 41, 1886],
 [1, 687, 4, 45, 41, 1886, 1887],
 [1, 687, 4, 45, 41, 1886, 1887],
 [1, 687, 4, 45, 41, 1886, 1887, 1888],
 [1, 687, 4, 45, 41, 1886, 1887, 1888],
 [1180, 1889],
 [1180, 1889],
 [1180, 1889, 1890],
 [1180, 1889, 1890],
 [1180, 1889, 1890, 1891],
 [1180, 1889, 1890, 1891],
 [57, 407],
 [57, 407],
 [57, 407, 2],
 [57, 407, 2],
 [57, 407, 2, 1181],
 [57, 407, 2, 1181],
 [57, 407, 2, 1181, 177],
 [57, 407, 2, 1181, 177],
 [57, 407, 2, 1181, 177, 1892],
 [57, 407, 2, 1181, 177, 1892],
 [407, 1182],
 [407, 1182],
 [407, 1182, 63],
 [407, 1182, 63],
 [408, 162],
 [408, 162],
 [408, 162, 377],
 [408, 162, 377],
 [408, 162, 377, 21],
 [408, 162, 377, 21],
 [408, 162, 377, 21, 247],
 [408, 162, 377, 21, 247],
 [408, 162, 377, 21, 247, 882],
 [408, 162, 377, 21, 247, 882],
 [18, 66],
 [18, 66],
 [451, 224],
 [451

In [17]:
max_sequence_len=max([len(x) for x in input_sequences])
max_sequence_len

14

In [18]:
input_sequences=np.array(pad_sequences(input_sequences, padding='pre'))
input_sequences

array([[   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       ...,
       [   0,    0,    0, ...,   45, 1047,    4],
       [   0,    0,    0, ..., 1047,    4,  193],
       [   0,    0,    0, ..., 1047,    4,  193]])

In [19]:
import tensorflow as tf
x,y=input_sequences[:,:-1],input_sequences[:,-1]


In [20]:
x

array([[   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    1,  687],
       ...,
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4],
       [   0,    0,    0, ...,   45, 1047,    4]])

In [21]:
y

array([687, 687,   4, ...,   4, 193, 193])

In [22]:
y=tf.keras.utils.to_categorical(y, num_classes=total_words)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2)

In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout


In [25]:
model=Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_len-1))
model.add(LSTM(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words, activation='softmax'))

In [26]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 13, 100)           481800    
                                                                 
 lstm (LSTM)                 (None, 13, 150)           150600    
                                                                 
 dropout (Dropout)           (None, 13, 150)           0         
                                                                 
 lstm_1 (LSTM)               (None, 100)               100400    
                                                                 
 dense (Dense)               (None, 4818)              486618    
                                                                 
Total params: 1219418 (4.65 MB)
Trainable params: 1219418 (4.65 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [27]:
history=model.fit(x_train,y_train, epochs=50,validation_data=(x_test,y_test),verbose=1)

Epoch 1/50


1287/1287 [==============================] - 47s 31ms/step - loss: 6.7386 - accuracy: 0.0347 - val_loss: 6.4988 - val_accuracy: 0.0427
Epoch 2/50
1287/1287 [==============================] - 39s 30ms/step - loss: 6.3077 - accuracy: 0.0473 - val_loss: 6.3148 - val_accuracy: 0.0513
Epoch 3/50
1287/1287 [==============================] - 43s 33ms/step - loss: 6.0308 - accuracy: 0.0597 - val_loss: 6.1306 - val_accuracy: 0.0692
Epoch 4/50
1287/1287 [==============================] - 41s 32ms/step - loss: 5.7761 - accuracy: 0.0751 - val_loss: 5.9910 - val_accuracy: 0.0753
Epoch 5/50
1287/1287 [==============================] - 41s 32ms/step - loss: 5.5570 - accuracy: 0.0845 - val_loss: 5.8742 - val_accuracy: 0.0881
Epoch 6/50
1287/1287 [==============================] - 41s 32ms/step - loss: 5.3539 - accuracy: 0.0949 - val_loss: 5.7852 - val_accuracy: 0.0937
Epoch 7/50
1287/1287 [==============================] - 35s 27ms/step - loss: 5.1575 - accuracy: 0.1028 - val_loss: 5.6973

In [28]:
def predict_next_word(model, tokenizer, text, max_sequence_len):
    token_list = tokenizer.texts_to_sequences([text])[0]
    if len(token_list) >= max_sequence_len:
        token_list = token_list[-(max_sequence_len-1):]  # Ensure the sequence length matches max_sequence_len-1
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = model.predict(token_list, verbose=0)
    predicted_word_index = np.argmax(predicted, axis=1)
    for word, index in tokenizer.word_index.items():
        if index == predicted_word_index:
            return word
    return None

In [29]:
input_text="To be or not to be"
print(f"Input text:{input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next Word PRediction:{next_word}")

Input text:To be or not to be
Next Word PRediction:a


In [30]:
model.save("next_word_lstm.h5")
import pickle
with open('tokenizer.pickle','wb') as handle:
    pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)

c:\Users\HP\OneDrive\Desktop\artificialnn\.venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
